language: ruby
bundler_args: --verbose
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
branches:
  only:
    - master
script: 'rake spec'
after_script: 'bundle exec guard-jasmine'
notifications:
  recipients:
    - michi@netzpiraten.ch
